### ISSUE TITLE
Stuck at 640x480 resolution with the Plasma desktop

### ISSUE THREAD

**Issue by gareth-anthony-hulse** [Fishwaldo/meta-pine64#10]
Resolution setting is stuck at 640x480 with image version 1.2, using the Plasma desktop. [Star64's wiki page says the GPU should support 4K](https://wiki.pine64.org/wiki/STAR64#GPU_Architecture).

**Comment by Fishwaldo** [comment]
Its most likely a driver issue. The driver has problems going above 1080p. The latest kernel 5.15.115 should help this a bit, but needs more testing. 

If it doesn't work, please reopen and post the output of ```more /sys/class/drm/card1-HDMI-A-1/modes```

**Comment by gareth-anthony-hulse** [comment]
With image version 1.3  I can set the resolution to 1024x768, but its still not quite 1080p.

output for `more /sys/class/drm/card1-HDMI-A-1/modes`:
```
1024x768
800x600
800x600
848x480
640x480
```
