### ISSUE TITLE
libsdl2 package doesn't include Wayland driver

### ISSUE THREAD

**Issue by Dillonb** [Fishwaldo/meta-pine64#15]
Unsure if this is related to removing the OpenGL backend. To reproduce, launch any SDL application with `SDL_VIDEODRIVER=wayland`

**Comment by Fishwaldo** [comment]
Should be fixed now. You can check configure output here: https://gist.github.com/Fishwaldo/1e769c75dc9f921794a14f3a7e12aa8c
