### ISSUE TITLE
Bug in weston and plasma images? "GPT:Primary header thinks Alt. header is not at the end of the disk"

### ISSUE THREAD

**Issue by bortzmeyer** [Fishwaldo/meta-pine64#2]
weston and plasma images of last night cannot be copied with dd. dmesg shows:

```
[13270.167883] GPT:5512041 != 30220287
[13270.167885] GPT:Alternate GPT header not at the end of the disk.
[13270.167886] GPT:5512041 != 30220287
[13270.167887] GPT: Use GNU Parted to correct GPT errors.
[13270.167897]  mmcblk0: p1 p2 p3 p4
[13278.372506] mmc0: card 0007 removed
```

minimal has no problem. (32 GB SanDisk microsSD card so I guess it is not a size issue. I tried with two cards to be sure.) Using GNU parted does not render the image usable.

**Comment by Fishwaldo** [comment]
This is just a initial message on first boot. Once fully booted, the partition is resized and this is no longer a issue. Can you confirm?

**Comment by bortzmeyer** [comment]
> This is just a initial message on first boot. Once fully booted, the partition is resized and this is no longer a issue. Can you confirm?

I infirm. With this SD card, the Star64 does not boot.

**Comment by bortzmeyer** [comment]
> > This is just a initial message on first boot. Once fully booted, the partition is resized and this is no longer a issue. Can you confirm?
> 
> I infirm. With this SD card, the Star64 does not boot.

I think I was not clear enough. I run dd on a laptop with Ubuntu. The error message is the one displayed by Ubuntu's kernel (probably when it tries to automount the filesystems on the card). Then, if I use this SD card in the Star64, the Star64 does not boot (no console yet, so I don't know if there is an error message)

**Comment by Fishwaldo** [comment]
You need to hook up a serial console to see u-boot messages and figure out why it's not booting.

**Comment by bortzmeyer** [comment]
> This is just a initial message on first boot. Once fully booted, the partition is resized and this is no longer a issue. Can you confirm?

OK, I was wrong, after some time, the SD card indeed works and the Star64 boots. I'm not sure of what happened, I'll have to check but sorry for the false alarm and thanks for all the work on these images. Really appreciated!

**Comment by Fishwaldo** [comment]
Ok first boot it resizes the root partition which can take some time. That’s probably what you saw.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
