### ISSUE TITLE
Warnings when running apt

### ISSUE THREAD

**Issue by bortzmeyer** [Fishwaldo/meta-pine64#6]
I don't know if they are serious:

```
W: No Hash entry in Release file /var/lib/apt/lists/partial/pine64.my-ho.st:8443_dists_pinix_all_binary-riscv64_._Release
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/pine64.my-ho.st:8443_dists_pinix_all_binary-riscv64_._Release
W: No Hash entry in Release file /var/lib/apt/lists/partial/pine64.my-ho.st:8443_dists_pinix_star64_binary-riscv64_._Release
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/pine64.my-ho.st:8443_dists_pinix_star64_binary-riscv64_._Release
W: No Hash entry in Release file /var/lib/apt/lists/partial/pine64.my-ho.st:8443_dists_pinix_riscv64_binary-riscv64_._Release
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/pine64.my-ho.st:8443_dists_pinix_riscv64_binary-riscv64_._Release
```

**Comment by Fishwaldo** [comment]
What Image are you running?

**Comment by bortzmeyer** [comment]
> What Image are you running?

weston 

I had to change the `sources.list` since apparently the organisation of the tree changed recently.

**Comment by Fishwaldo** [comment]
Did you upgrade the image? The original images are not compatible with with the new apt repository.

(Shouldn’t have to change that again)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bortzmeyer** [comment]
> Did you upgrade the image? The original images are not compatible with with the new apt repository. (Shouldn’t have to change that again) 

Hmmm, OK. What are the solutions? Start from scratch with one of the new images?

**Comment by Fishwaldo** [comment]
You can try a apt upgrade but I don't know if it will work afterwards... so save anything important...

**Comment by bortzmeyer** [comment]
Moved directly to 1.2 (after backup and before restore), everything works.
