### ISSUE TITLE
apt does not work on the minimal image

### ISSUE THREAD

**Issue by bortzmeyer** [Fishwaldo/meta-pine64#7]
When booting on the last minimal image (star64-image-minimal-star64-1.2.wic.bz2, 05/17/2023, 07:44:43 PM), ` apt update` does not work:

`star64:~# apt update
Ign:1 https://pine64.my-ho.st:8443/deb/all ./ InRelease
Ign:2 https://pine64.my-ho.st:8443/deb/star64 ./ InRelease
Ign:3 https://pine64.my-ho.st:8443/deb/riscv64 ./ InRelease
Ign:4 https://pine64.my-ho.st:8443/deb/all ./ Release
Ign:5 https://pine64.my-ho.st:8443/deb/star64 ./ Release
Ign:6 https://pine64.my-ho.st:8443/deb/riscv64 ./ Release
Ign:7 https://pine64.my-ho.st:8443/deb/all ./ Packages
Ign:8 https://pine64.my-ho.st:8443/deb/all ./ Translation-en
Ign:9 https://pine64.my-ho.st:8443/deb/star64 ./ Packages
Ign:10 https://pine64.my-ho.st:8443/deb/star64 ./ Translation-en
Ign:11 https://pine64.my-ho.st:8443/deb/riscv64 ./ Packages
Ign:12 https://pine64.my-ho.st:8443/deb/riscv64 ./ Translation-en
Ign:7 https://pine64.my-ho.st:8443/deb/all ./ Packages
Ign:8 https://pine64.my-ho.st:8443/deb/all ./ Translation-en
Ign:9 https://pine64.my-ho.st:8443/deb/star64 ./ Packages
Ign:10 https://pine64.my-ho.st:8443/deb/star64 ./ Translation-en
Ign:11 https://pine64.my-ho.st:8443/deb/riscv64 ./ Packages
Ign:12 https://pine64.my-ho.st:8443/deb/riscv64 ./ Translation-en
Ign:7 https://pine64.my-ho.st:8443/deb/all ./ Packages
Ign:8 https://pine64.my-ho.st:8443/deb/all ./ Translation-en
Ign:9 https://pine64.my-ho.st:8443/deb/star64 ./ Packages
Ign:10 https://pine64.my-ho.st:8443/deb/star64 ./ Translation-en
Ign:11 https://pine64.my-ho.st:8443/deb/riscv64 ./ Packages
Ign:12 https://pine64.my-ho.st:8443/deb/riscv64 ./ Translation-en
Ign:7 https://pine64.my-ho.st:8443/deb/all ./ Packages
Ign:8 https://pine64.my-ho.st:8443/deb/all ./ Translation-en
Ign:9 https://pine64.my-ho.st:8443/deb/star64 ./ Packages
Ign:10 https://pine64.my-ho.st:8443/deb/star64 ./ Translation-en
Ign:11 https://pine64.my-ho.st:8443/deb/riscv64 ./ Packages
Ign:12 https://pine64.my-ho.st:8443/deb/riscv64 ./ Translation-en
Ign:7 https://pine64.my-ho.st:8443/deb/all ./ Packages
Ign:8 https://pine64.my-ho.st:8443/deb/all ./ Translation-en
Ign:9 https://pine64.my-ho.st:8443/deb/star64 ./ Packages
Ign:10 https://pine64.my-ho.st:8443/deb/star64 ./ Translation-en
Ign:11 https://pine64.my-ho.st:8443/deb/riscv64 ./ Packages
Ign:12 https://pine64.my-ho.st:8443/deb/riscv64 ./ Translation-en
Err:7 https://pine64.my-ho.st:8443/deb/all ./ Packages
  404  Not Found [IP: 103.208.176.191 8443]
Ign:8 https://pine64.my-ho.st:8443/deb/all ./ Translation-en
Err:9 https://pine64.my-ho.st:8443/deb/star64 ./ Packages
  404  Not Found [IP: 103.208.176.191 8443]
Ign:10 https://pine64.my-ho.st:8443/deb/star64 ./ Translation-en
Err:11 https://pine64.my-ho.st:8443/deb/riscv64 ./ Packages
  404  Not Found [IP: 103.208.176.191 8443]
Ign:12 https://pine64.my-ho.st:8443/deb/riscv64 ./ Translation-en
Reading package lists... Done
E: Failed to fetch https://pine64.my-ho.st:8443/deb/all/./Packages  404  Not Found [IP: 103.208.176.191 8443]
E: Failed to fetch https://pine64.my-ho.st:8443/deb/star64/./Packages  404  Not Found [IP: 103.208.176.191 8443]
E: Failed to fetch https://pine64.my-ho.st:8443/deb/riscv64/./Packages  404  Not Found [IP: 103.208.176.191 8443]
E: Some index files failed to download. They have been ignored, or old ones used instead.
``

```

**Comment by Fishwaldo** [comment]
Are you sure thats a 1.2 image? please check /etc/os-release

**Comment by bortzmeyer** [comment]
> Are you sure thats a 1.2 image? please check /etc/os-release

```
star64:~$ cat /etc/os-release 
ID=pinix
NAME="PinIx"
VERSION="1.0 (pinix)"
VERSION_ID=1.0
PRETTY_NAME="PinIx 1.0 (pinix)"
DISTRO_CODENAME="pinix"
```

I downloaded  https://pine64.my-ho.st:8443/star64-image-minimal-star64-1.2.wic.bz2, dd to the card and booted on it.

**Comment by Fishwaldo** [comment]
Please double check. If confirmed the image is 1.2.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bortzmeyer** [comment]
I'm investigating. Currently, I'm looking for a way to examine the WIC image before burning it to the SD-card. I found instructions https://docs.yoctoproject.org/dev-manual/wic.html https://imxdev.gitlab.io/tutorial/How_to_inspect_OpenEmbedded_kickstart_wic_files/ but no clear way about how to build the `wic` command. I assume I have to install first the entire Yocto system :-(

**Comment by Fishwaldo** [comment]
It’s just a normal image produced by a tool called wic. You can just use a loop device to mount like any other image.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bortzmeyer** [comment]
OK, I'm note sure of what happened but by re-doing everything carefully, it now works. I close the ticket (and will give some explanations later), sorry for the false alarm.

**Comment by bortzmeyer** [comment]
To mount the Unix filesystem in the `.wic` image, the procedure is:

1. Find the start of this filesystem in sectors with `fdisk -l star64-image-minimal-star64-1.2.wic` 
2. Multiply by the size of a sector (typically 512). Here, we get 406847488
3. sudo mount -o loop,offset=406847488 star64-image-minimal-star64-1.2.wic /mnt
