### ISSUE TITLE
gcc/g++ fail to build "as" missing

### ISSUE THREAD

**Issue by lehitoskin** [Fishwaldo/meta-pine64#8]
I installed gcc and g++ with `apt install gcc g++` and I can't even compile a simple "Hello World!" program because it says `as` is missing.

```
~> gcc -o foo_c foo.c
gcc: fatal error: cannot execute 'as': execvp: No such file or directory
compilation terminated.
```

Is this supplied by another package or something?

**Comment by Fishwaldo** [comment]
use 
```apt install packagegroup-core-sdk```

**Comment by lehitoskin** [comment]
Ah-ha! That did it. Thank you!
